name: '🧪 Run Test Suite'

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup variables
        shell: bash
        run: |-
          echo "YEAR_WEEK=$(date -u '+%Y%W')" >> $GITHUB_ENV

      - name: Cache NuGet dependencies
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ env.YEAR_WEEK }}

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Run tests
        shell: bash
        run: |-
          for testProj in tests/*/*Tests.csproj; do
            dotnet test ${testProj} \
              --configuration Release \
              --collect:"XPlat Code Coverage" \
              --results-directory TestResults/ \
              --settings tests/coverletArgs.runsettings \
              --verbosity minimal \
              --nologo
          done

      - name: Publish test reults
        uses: dorny/test-reporter@v1
        if: ${{ success() || failure() }}
        with:
          name: Jellyfin Tests (${{ matrix.os }})
          path: TestResults/**/*.trx
          reporter: dotnet-trx
