name: '🚀 Publish OS Packages'

on:
#  push:
#    branches:
#      - master
#      - main
#    tags:
#      - 'v*'
  workflow_dispatch:

jobs:
  build-packages:
    name: Build Server Packages
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        build-config:
          - centos.amd64
          - fedora.amd64
          - debian.amd64
          - debian.arm64
          - debian.armhf
          - ubuntu.amd64
          - ubuntu.arm64
          - ubuntu.armhf
          - linux.amd64
          - linux.amd64-musl
          - linux.arm64
          - linux.armhf
          - windows.amd64
          - macos
          - portable
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build Packaging Container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: jellyfin-server
          tags: ${{ matrix.build-config }}
          oci: true
          dockerfiles: deployment/Dockerfile.${{ matrix.build-config }}

      - name: Run Packaging Container (stable)
        if: ${{ contains(github.ref, 'refs/tags/v') }}
        run: |-
          mkdir -p deployment/dist
          podman run --rm \
            -v $(pwd)/deployment/dist:/dist \
            -v $(pwd):/jellyfin \
            -e IS_UNSTABLE="no" \
            -e BUILD_ID=${{ github.run_id }} \
            jellyfin-server:${{ matrix.build-config }}

      - name: Run Packaging Container (unstable)
        if: ${{ ! contains(github.ref, 'refs/tags/v') }}
        run: |-
          mkdir -p deployment/dist
          podman run --rm \
            -v $(pwd)/deployment/dist:/dist \
            -v $(pwd):/jellyfin \
            -e IS_UNSTABLE="yes" \
            -e BUILD_ID=${{ github.run_id }} \
            jellyfin-server:${{ matrix.build-config }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jellyfin-server-${{ matrix.build-config }}
          path: deployment/dist
